### ISSUE TITLE
Required field weirdness

### ISSUE THREAD

**Issue by andrewminton** [brockpetrie/dynamictextgroup#1]
Hey Brock, Trying this out on a local install, 2.2.3 and dev branch of extension.

I checked the required field for the extension and whenever I add new text group and click save, it says that my field is Required... but it's not empty, so shouldn't error. 

See screen grab of what I see when I try and save: https://dl-web.dropbox.com/get/Public/Screen%20shot%202011-09-17%20at%2012.22.21.png?w=c56465e7

I'm using the select field for manual Yes, No drop down options and a textfield for the entry text.

**Comment by brockpetrie** [comment]
Thanks Andrew, nice catch. I accidentally deleted a line while doing some code clean-up, so you can solve this problem quite easily by changing [lines 276-277](https://github.com/brockpetrie/dynamictextgroup/blob/development/fields/field.dynamictextgroup.php#L276-277) in `field.dynamictextgroup.php` to the following:

``` php
if ($req && $data[$field->handle][$i] == '') {
    $emptyReq = true;
} else if ($data[$field->handle][$i] != '') {   
    $empty = false;
    $emptyRow = false;
}
```

That should fix it. Let me know if you find any other bugs and I'll get those fixed for the next commit as well. Thanks again, man!

**Comment by andrewminton** [comment]
Cool, 

One thing I noticed when creating an event using this extension is that the samplefield name is retained in the sample code.. i.e I forgot to name my second field to [correct].. so went and re edited the section and named it to "correct" but in the event samplecode it still says 

```
<label>Answers
<input name="fields[answers][samplefield][]" type="text" />
</label>
```

Is this the desired behaviour or is it not saving fieldname alterations back to the DB?

**Comment by brockpetrie** [comment]
First let me preface this by saying that I didn't update the sample code generator, so it's not generating the correct markup to begin with. This will be fixed in the next commit— thanks for pointing it out.

But to the gist of your question: the documentation (which the includes the sample code) for an event is generated when that event is first created, and is saved in the event's file in your `/workspace/events` directory. To my knowledge, there is no way to easily modify the contents of that file after it's been created (otherwise it'd overwrite any customizations that you made to that file). So even after I get the sample code generation working, the sample code will not be updated when you rename your subfields (or make any Dynamic Text Group modifications for that matter); you'll have to delete and recreate the event to have the documentation reflect the subfield changes.

So you'll just have to remember that the sample code won't be accurate after making any changes to the field. I should also note that the documentation doesn't have any bearing on the functionality of the event/extension; as long as your front-end form fields match the back-end form fields you'll be fine. If you add a subfield with the extension, you'll have to add a field to the front-end.

I'll probably have to add some sort of note to the generated sample code that warns people about that.

**Comment by andrewminton** [comment]
Hi Brock, gotcha. Didn't know that was the case, so thanks for clearing what happens. The event was created after I had already amended the Section to include the [Correct] naming for my field. So I guess updating the sample code generation on commit will reflect when Event is first created... 

Loving what this offers users as far as functionality goes.. Checkboxes and Radio buttons, WOULD be ace.. so much potential for Quiz/Questionaires in my eyes :)

**Comment by brockpetrie** [comment]
Working on checks and radios now; they'll be in the next commit! :)

**Comment by andrewminton** [comment]
Oooh exciting, Virtual high five coming your way! this is gonna be ace. I gotta feeling the Symphony community will send more high fives your way :) laters.
